"""학생 공지 체크리스트 초기 스키마

Revision ID: 65d23b502c33
Revises:
Create Date: 2026-09-16 19:56:29.384837
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65d23b502c33"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("message_ts", sa.String(length=32), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("source_permalink", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_source_text", sa.Text(), nullable=True),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ('processed', 'processing_failed', 'ai_disabled')",
            name="ck_notices_processing_status",
        ),
        sa.CheckConstraint("retry_count >= 0", name="ck_notices_retry_count_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "canonical_url", name="uq_notices_workspace_canonical_url"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "channel_id",
            "message_ts",
            "canonical_url",
            name="uq_notices_source_link",
        ),
    )
    op.create_index(
        "ix_notices_source_message",
        "notices",
        ["workspace_id", "channel_id", "message_ts"],
        unique=False,
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("slack_user_id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("campus", sa.String(length=32), nullable=False),
        sa.Column("class_number", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("class_number > 0", name="ck_students_class_number_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "slack_user_id", name="uq_students_workspace_slack_user"
        ),
    )
    op.create_index(
        "ix_students_affiliation",
        "students",
        ["workspace_id", "campus", "class_number"],
        unique=False,
    )
    op.create_table(
        "checklists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("notice_id", sa.Uuid(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notice_id"], ["notices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "notice_id", name="uq_checklists_student_notice"),
    )
    op.create_index("ix_checklists_notice_id", "checklists", ["notice_id"], unique=False)
    op.create_index(
        "ix_checklists_student_active", "checklists", ["student_id", "deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_checklists_student_active", table_name="checklists")
    op.drop_index("ix_checklists_notice_id", table_name="checklists")
    op.drop_table("checklists")
    op.drop_index("ix_students_affiliation", table_name="students")
    op.drop_table("students")
    op.drop_index("ix_notices_source_message", table_name="notices")
    op.drop_table("notices")
    # ### end Alembic commands ###
